--
-- PostgreSQL database dump
--

\restrict uBlyrrHtgPRbnbG57vkKboiyL4hK1mNGXy8TKeHxtbN7UyBc870PtrfKX2RlGxb

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actividades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.actividades (
    id_actividad integer NOT NULL,
    id_paciente integer NOT NULL,
    nombre_actividad character varying(100) NOT NULL,
    descripcion text,
    fecha_asignacion timestamp with time zone DEFAULT now() NOT NULL,
    estado_actividad character varying(20) NOT NULL
);


--
-- Name: actividades_id_actividad_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.actividades ALTER COLUMN id_actividad ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actividades_id_actividad_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: administradores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.administradores (
    id_administrador integer NOT NULL,
    id_usuario integer NOT NULL,
    fecha_creacion timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: administradores_id_administrador_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.administradores ALTER COLUMN id_administrador ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.administradores_id_administrador_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auditoria_cambios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auditoria_cambios (
    id_auditoria integer NOT NULL,
    id_usuario_actor integer,
    nombre_tabla character varying(50) NOT NULL,
    nombre_entidad character varying(50) NOT NULL,
    accion character varying(12) NOT NULL,
    datos_anteriores jsonb,
    datos_nuevos jsonb,
    fecha_evento timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: auditoria_cambios_id_auditoria_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auditoria_cambios ALTER COLUMN id_auditoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_cambios_id_auditoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversaciones (
    id_conversacion integer NOT NULL,
    id_tutor integer NOT NULL,
    id_terapeuta integer,
    estado character varying(20) NOT NULL,
    fecha_creacion timestamp with time zone DEFAULT now() NOT NULL,
    ultima_actividad timestamp with time zone DEFAULT now() NOT NULL,
    fecha_archivado timestamp with time zone
);


--
-- Name: conversaciones_id_conversacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conversaciones ALTER COLUMN id_conversacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversaciones_id_conversacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluaciones_ia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evaluaciones_ia (
    id_evaluacion_ia integer NOT NULL,
    id_paciente integer NOT NULL,
    id_reporte_sesion integer NOT NULL,
    id_resultado_nivel integer,
    resultado_json_ia jsonb,
    recomendaciones text,
    estado_revision character varying(20) NOT NULL,
    fecha_evaluacion timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: evaluaciones_ia_id_evaluacion_ia_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.evaluaciones_ia ALTER COLUMN id_evaluacion_ia ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluaciones_ia_id_evaluacion_ia_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expedientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expedientes (
    id_expediente integer NOT NULL,
    id_paciente integer NOT NULL,
    historial_clinico text,
    diagnostico_inicial text,
    fecha_apertura timestamp with time zone DEFAULT now() NOT NULL,
    fecha_actualizacion timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: expedientes_id_expediente_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.expedientes ALTER COLUMN id_expediente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expedientes_id_expediente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: logros; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.logros (
    id_logro integer NOT NULL,
    nombre_logro character varying(100) NOT NULL,
    experiencia_logro integer DEFAULT 0 NOT NULL,
    requisito_logro text NOT NULL,
    icono_logro character varying(255),
    CONSTRAINT chk_logros_experiencia CHECK ((experiencia_logro >= 0))
);


--
-- Name: logros_id_logro_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.logros ALTER COLUMN id_logro ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.logros_id_logro_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensaje_adjuntos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mensaje_adjuntos (
    id_adjunto integer NOT NULL,
    id_mensaje integer NOT NULL,
    url_archivo character varying(255) NOT NULL,
    nombre_archivo character varying(255) NOT NULL,
    mime_type character varying(100) NOT NULL,
    tamano_bytes bigint NOT NULL,
    duracion_segundos integer,
    CONSTRAINT chk_mensaje_adjuntos_duracion CHECK (((duracion_segundos IS NULL) OR (duracion_segundos >= 0))),
    CONSTRAINT chk_mensaje_adjuntos_tamano CHECK ((tamano_bytes >= 0))
);


--
-- Name: mensaje_adjuntos_id_adjunto_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mensaje_adjuntos ALTER COLUMN id_adjunto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensaje_adjuntos_id_adjunto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensajes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mensajes (
    id_mensaje integer NOT NULL,
    id_conversacion integer NOT NULL,
    id_usuario_emisor integer,
    texto_mensaje text,
    fecha_envio timestamp with time zone DEFAULT now() NOT NULL,
    leido boolean DEFAULT false NOT NULL
);


--
-- Name: mensajes_id_mensaje_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mensajes ALTER COLUMN id_mensaje ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensajes_id_mensaje_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mundos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mundos (
    id_mundo integer NOT NULL,
    id_actividad integer NOT NULL,
    nombre_mundo character varying(30) NOT NULL,
    descripcion text,
    objetivo text,
    activo boolean DEFAULT true NOT NULL
);


--
-- Name: mundos_id_mundo_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mundos ALTER COLUMN id_mundo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mundos_id_mundo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: niveles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.niveles (
    id_nivel integer NOT NULL,
    id_mundo integer NOT NULL,
    nombre_nivel character varying(100) NOT NULL,
    orden integer NOT NULL,
    objetivo text,
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT chk_niveles_orden CHECK ((orden > 0))
);


--
-- Name: niveles_id_nivel_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.niveles ALTER COLUMN id_nivel ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.niveles_id_nivel_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: objetivos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.objetivos (
    id_objetivo integer NOT NULL,
    id_actividad integer NOT NULL,
    titulo character varying(20) NOT NULL,
    descripcion text,
    resultados_objetivo jsonb
);


--
-- Name: objetivos_id_objetivo_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.objetivos ALTER COLUMN id_objetivo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.objetivos_id_objetivo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pacientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pacientes (
    id_paciente integer NOT NULL,
    id_tutor integer NOT NULL,
    nombres_paciente character varying(60) NOT NULL,
    apellidos_paciente character varying(80) NOT NULL,
    fecha_nacimiento date NOT NULL,
    sexo character varying(10) NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    fecha_registro timestamp with time zone DEFAULT now() NOT NULL,
    avatar_nombre character varying(20) DEFAULT 'zorro'::character varying NOT NULL
);


--
-- Name: pacientes_id_paciente_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pacientes ALTER COLUMN id_paciente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pacientes_id_paciente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: perfil_logros; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.perfil_logros (
    id_perfil_logro integer NOT NULL,
    id_perfil integer NOT NULL,
    id_logro integer NOT NULL,
    fecha_obtencion timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: perfil_logros_id_perfil_logro_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.perfil_logros ALTER COLUMN id_perfil_logro ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.perfil_logros_id_perfil_logro_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: perfiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.perfiles (
    id_perfil integer NOT NULL,
    id_paciente integer NOT NULL,
    progreso numeric(5,2) DEFAULT 0 NOT NULL,
    racha_dias integer DEFAULT 0 NOT NULL,
    objetivos_totales integer DEFAULT 0 NOT NULL,
    objetivos_completados integer DEFAULT 0 NOT NULL,
    actividades_desarrolladas_total integer DEFAULT 0 NOT NULL,
    sesiones_totales integer DEFAULT 0 NOT NULL,
    fecha_ultima_sesion timestamp with time zone,
    experiencia integer DEFAULT 0 NOT NULL,
    nivel integer DEFAULT 1 NOT NULL,
    CONSTRAINT chk_perfiles_actividades CHECK ((actividades_desarrolladas_total >= 0)),
    CONSTRAINT chk_perfiles_experiencia CHECK ((experiencia >= 0)),
    CONSTRAINT chk_perfiles_nivel CHECK ((nivel >= 1)),
    CONSTRAINT chk_perfiles_objetivos_completados CHECK ((objetivos_completados >= 0)),
    CONSTRAINT chk_perfiles_objetivos_totales CHECK ((objetivos_totales >= 0)),
    CONSTRAINT chk_perfiles_progreso CHECK (((progreso >= (0)::numeric) AND (progreso <= (100)::numeric))),
    CONSTRAINT chk_perfiles_racha CHECK ((racha_dias >= 0)),
    CONSTRAINT chk_perfiles_sesiones CHECK ((sesiones_totales >= 0))
);


--
-- Name: perfiles_id_perfil_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.perfiles ALTER COLUMN id_perfil ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.perfiles_id_perfil_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reportes_sesion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reportes_sesion (
    id_reporte_sesion integer NOT NULL,
    id_sesion integer NOT NULL,
    observaciones_iniciales text,
    objetivos_trabajados text,
    nivel_ayuda text,
    proximos_pasos text,
    fecha_creacion timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: reportes_sesion_id_reporte_sesion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reportes_sesion ALTER COLUMN id_reporte_sesion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reportes_sesion_id_reporte_sesion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservas (
    id_reserva integer NOT NULL,
    id_paciente integer NOT NULL,
    id_terapeuta integer NOT NULL,
    id_tratamiento integer NOT NULL,
    fecha_hora_inicio timestamp with time zone NOT NULL,
    fecha_hora_fin timestamp with time zone NOT NULL,
    modalidad character varying(10) NOT NULL,
    localizacion character varying(255),
    zoom_meeting_id character varying(8),
    zoom_join_url character varying(255),
    estado_reserva character varying(20) NOT NULL,
    fecha_creacion timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_reservas_fechas CHECK ((fecha_hora_fin > fecha_hora_inicio))
);


--
-- Name: reservas_id_reserva_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservas ALTER COLUMN id_reserva ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_id_reserva_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resultados_nivel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resultados_nivel (
    id_resultado_nivel integer NOT NULL,
    id_paciente integer NOT NULL,
    id_nivel integer NOT NULL,
    numero_intento integer NOT NULL,
    puntaje integer,
    estrellas_obtenidas integer,
    detalle_resultados jsonb,
    fecha_realizacion timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_resultados_estrellas CHECK (((estrellas_obtenidas IS NULL) OR (estrellas_obtenidas >= 0))),
    CONSTRAINT chk_resultados_numero_intento CHECK ((numero_intento > 0)),
    CONSTRAINT chk_resultados_puntaje CHECK (((puntaje IS NULL) OR (puntaje >= 0)))
);


--
-- Name: resultados_nivel_id_resultado_nivel_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resultados_nivel ALTER COLUMN id_resultado_nivel ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resultados_nivel_id_resultado_nivel_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id_rol integer NOT NULL,
    nombre_rol character varying(12) NOT NULL,
    descripcion character varying(150),
    fecha_creacion timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: roles_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sesiones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sesiones (
    id_sesion integer NOT NULL,
    id_reserva integer NOT NULL,
    fecha_hora_inicio_real timestamp with time zone,
    fecha_hora_fin_real timestamp with time zone,
    asistencia character varying(20),
    estado_sesion character varying(20) NOT NULL,
    CONSTRAINT chk_sesiones_fechas CHECK (((fecha_hora_fin_real IS NULL) OR (fecha_hora_inicio_real IS NULL) OR (fecha_hora_fin_real > fecha_hora_inicio_real)))
);


--
-- Name: sesiones_autenticacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sesiones_autenticacion (
    id_sesion_auth integer NOT NULL,
    id_usuario integer NOT NULL,
    token_hash character varying(255) NOT NULL,
    fecha_emision timestamp with time zone DEFAULT now() NOT NULL,
    fecha_expiracion timestamp with time zone NOT NULL,
    ultima_actividad timestamp with time zone DEFAULT now() NOT NULL,
    mfa_verificado boolean DEFAULT false NOT NULL,
    revocado boolean DEFAULT false NOT NULL,
    fecha_cierre timestamp with time zone
);


--
-- Name: sesiones_autenticacion_id_sesion_auth_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sesiones_autenticacion ALTER COLUMN id_sesion_auth ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sesiones_autenticacion_id_sesion_auth_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sesiones_id_sesion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sesiones ALTER COLUMN id_sesion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sesiones_id_sesion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: terapeutas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.terapeutas (
    id_terapeuta integer NOT NULL,
    id_usuario integer NOT NULL,
    especialidad character varying(100),
    anios_experiencia integer,
    idiomas character varying(50),
    descripcion_profesional text,
    CONSTRAINT chk_terapeutas_experiencia CHECK (((anios_experiencia IS NULL) OR (anios_experiencia >= 0)))
);


--
-- Name: terapeutas_id_terapeuta_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.terapeutas ALTER COLUMN id_terapeuta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terapeutas_id_terapeuta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tratamientos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tratamientos (
    id_tratamiento integer NOT NULL,
    id_expediente integer NOT NULL,
    id_terapeuta integer NOT NULL,
    nombre_tratamiento character varying(100) NOT NULL,
    descripcion text,
    sesiones_recomendadas integer,
    estado_tratamiento character varying(20) NOT NULL,
    fecha_inicio date,
    fecha_fin date,
    observaciones_cierre text,
    CONSTRAINT chk_tratamientos_sesiones CHECK (((sesiones_recomendadas IS NULL) OR (sesiones_recomendadas >= 0)))
);


--
-- Name: tratamientos_id_tratamiento_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tratamientos ALTER COLUMN id_tratamiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tratamientos_id_tratamiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tutores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tutores (
    id_tutor integer NOT NULL,
    id_usuario integer NOT NULL,
    parentesco character varying(30),
    telefono character varying(12),
    direccion character varying(200)
);


--
-- Name: tutores_id_tutor_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tutores ALTER COLUMN id_tutor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tutores_id_tutor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_roles (
    id_usuario_rol integer NOT NULL,
    id_usuario integer NOT NULL,
    id_rol integer NOT NULL,
    asignado_por integer,
    fecha_asignacion timestamp with time zone DEFAULT now() NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


--
-- Name: usuario_roles_id_usuario_rol_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario_roles ALTER COLUMN id_usuario_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_roles_id_usuario_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id_usuario integer NOT NULL,
    nombres character varying(60) NOT NULL,
    apellidos character varying(80) NOT NULL,
    codigo_usuario character varying(6) NOT NULL,
    email character varying(150) NOT NULL,
    password_hash character varying(255) NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actividades actividades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actividades
    ADD CONSTRAINT actividades_pkey PRIMARY KEY (id_actividad);


--
-- Name: administradores administradores_id_usuario_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT administradores_id_usuario_key UNIQUE (id_usuario);


--
-- Name: administradores administradores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT administradores_pkey PRIMARY KEY (id_administrador);


--
-- Name: auditoria_cambios auditoria_cambios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria_cambios
    ADD CONSTRAINT auditoria_cambios_pkey PRIMARY KEY (id_auditoria);


--
-- Name: conversaciones conversaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversaciones
    ADD CONSTRAINT conversaciones_pkey PRIMARY KEY (id_conversacion);


--
-- Name: evaluaciones_ia evaluaciones_ia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones_ia
    ADD CONSTRAINT evaluaciones_ia_pkey PRIMARY KEY (id_evaluacion_ia);


--
-- Name: expedientes expedientes_id_paciente_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expedientes
    ADD CONSTRAINT expedientes_id_paciente_key UNIQUE (id_paciente);


--
-- Name: expedientes expedientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expedientes
    ADD CONSTRAINT expedientes_pkey PRIMARY KEY (id_expediente);


--
-- Name: logros logros_nombre_logro_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logros
    ADD CONSTRAINT logros_nombre_logro_key UNIQUE (nombre_logro);


--
-- Name: logros logros_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logros
    ADD CONSTRAINT logros_pkey PRIMARY KEY (id_logro);


--
-- Name: mensaje_adjuntos mensaje_adjuntos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensaje_adjuntos
    ADD CONSTRAINT mensaje_adjuntos_pkey PRIMARY KEY (id_adjunto);


--
-- Name: mensajes mensajes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT mensajes_pkey PRIMARY KEY (id_mensaje);


--
-- Name: mundos mundos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mundos
    ADD CONSTRAINT mundos_pkey PRIMARY KEY (id_mundo);


--
-- Name: niveles niveles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.niveles
    ADD CONSTRAINT niveles_pkey PRIMARY KEY (id_nivel);


--
-- Name: objetivos objetivos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objetivos
    ADD CONSTRAINT objetivos_pkey PRIMARY KEY (id_objetivo);


--
-- Name: pacientes pacientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT pacientes_pkey PRIMARY KEY (id_paciente);


--
-- Name: perfil_logros perfil_logros_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfil_logros
    ADD CONSTRAINT perfil_logros_pkey PRIMARY KEY (id_perfil_logro);


--
-- Name: perfiles perfiles_id_paciente_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfiles
    ADD CONSTRAINT perfiles_id_paciente_key UNIQUE (id_paciente);


--
-- Name: perfiles perfiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfiles
    ADD CONSTRAINT perfiles_pkey PRIMARY KEY (id_perfil);


--
-- Name: reportes_sesion reportes_sesion_id_sesion_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reportes_sesion
    ADD CONSTRAINT reportes_sesion_id_sesion_key UNIQUE (id_sesion);


--
-- Name: reportes_sesion reportes_sesion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reportes_sesion
    ADD CONSTRAINT reportes_sesion_pkey PRIMARY KEY (id_reporte_sesion);


--
-- Name: reservas reservas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT reservas_pkey PRIMARY KEY (id_reserva);


--
-- Name: resultados_nivel resultados_nivel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resultados_nivel
    ADD CONSTRAINT resultados_nivel_pkey PRIMARY KEY (id_resultado_nivel);


--
-- Name: roles roles_nombre_rol_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_nombre_rol_key UNIQUE (nombre_rol);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id_rol);


--
-- Name: sesiones_autenticacion sesiones_autenticacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesiones_autenticacion
    ADD CONSTRAINT sesiones_autenticacion_pkey PRIMARY KEY (id_sesion_auth);


--
-- Name: sesiones sesiones_id_reserva_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesiones
    ADD CONSTRAINT sesiones_id_reserva_key UNIQUE (id_reserva);


--
-- Name: sesiones sesiones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesiones
    ADD CONSTRAINT sesiones_pkey PRIMARY KEY (id_sesion);


--
-- Name: terapeutas terapeutas_id_usuario_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terapeutas
    ADD CONSTRAINT terapeutas_id_usuario_key UNIQUE (id_usuario);


--
-- Name: terapeutas terapeutas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terapeutas
    ADD CONSTRAINT terapeutas_pkey PRIMARY KEY (id_terapeuta);


--
-- Name: tratamientos tratamientos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tratamientos
    ADD CONSTRAINT tratamientos_pkey PRIMARY KEY (id_tratamiento);


--
-- Name: tutores tutores_id_usuario_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutores
    ADD CONSTRAINT tutores_id_usuario_key UNIQUE (id_usuario);


--
-- Name: tutores tutores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutores
    ADD CONSTRAINT tutores_pkey PRIMARY KEY (id_tutor);


--
-- Name: perfil_logros uq_perfil_logro; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfil_logros
    ADD CONSTRAINT uq_perfil_logro UNIQUE (id_perfil, id_logro);


--
-- Name: usuario_roles uq_usuario_rol; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT uq_usuario_rol UNIQUE (id_usuario, id_rol);


--
-- Name: usuario_roles usuario_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT usuario_roles_pkey PRIMARY KEY (id_usuario_rol);


--
-- Name: usuarios usuarios_codigo_usuario_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_codigo_usuario_key UNIQUE (codigo_usuario);


--
-- Name: usuarios usuarios_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario);


--
-- Name: idx_actividades_paciente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_actividades_paciente ON public.actividades USING btree (id_paciente);


--
-- Name: idx_auditoria_fecha_evento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_fecha_evento ON public.auditoria_cambios USING btree (fecha_evento);


--
-- Name: idx_auditoria_tabla_entidad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_tabla_entidad ON public.auditoria_cambios USING btree (nombre_tabla, nombre_entidad);


--
-- Name: idx_auditoria_usuario_actor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auditoria_usuario_actor ON public.auditoria_cambios USING btree (id_usuario_actor);


--
-- Name: idx_conversaciones_terapeuta; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_conversaciones_terapeuta ON public.conversaciones USING btree (id_terapeuta);


--
-- Name: idx_conversaciones_tutor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_conversaciones_tutor ON public.conversaciones USING btree (id_tutor);


--
-- Name: idx_evaluaciones_ia_paciente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evaluaciones_ia_paciente ON public.evaluaciones_ia USING btree (id_paciente);


--
-- Name: idx_evaluaciones_ia_reporte; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evaluaciones_ia_reporte ON public.evaluaciones_ia USING btree (id_reporte_sesion);


--
-- Name: idx_evaluaciones_ia_resultado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evaluaciones_ia_resultado ON public.evaluaciones_ia USING btree (id_resultado_nivel);


--
-- Name: idx_mensaje_adjuntos_mensaje; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mensaje_adjuntos_mensaje ON public.mensaje_adjuntos USING btree (id_mensaje);


--
-- Name: idx_mensajes_conversacion; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mensajes_conversacion ON public.mensajes USING btree (id_conversacion);


--
-- Name: idx_mensajes_emisor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mensajes_emisor ON public.mensajes USING btree (id_usuario_emisor);


--
-- Name: idx_mundos_actividad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mundos_actividad ON public.mundos USING btree (id_actividad);


--
-- Name: idx_niveles_mundo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_niveles_mundo ON public.niveles USING btree (id_mundo);


--
-- Name: idx_objetivos_actividad; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_objetivos_actividad ON public.objetivos USING btree (id_actividad);


--
-- Name: idx_pacientes_tutor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pacientes_tutor ON public.pacientes USING btree (id_tutor);


--
-- Name: idx_perfil_logros_logro; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_perfil_logros_logro ON public.perfil_logros USING btree (id_logro);


--
-- Name: idx_perfil_logros_perfil; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_perfil_logros_perfil ON public.perfil_logros USING btree (id_perfil);


--
-- Name: idx_perfiles_paciente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_perfiles_paciente ON public.perfiles USING btree (id_paciente);


--
-- Name: idx_reservas_fecha_inicio; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reservas_fecha_inicio ON public.reservas USING btree (fecha_hora_inicio);


--
-- Name: idx_reservas_paciente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reservas_paciente ON public.reservas USING btree (id_paciente);


--
-- Name: idx_reservas_terapeuta; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reservas_terapeuta ON public.reservas USING btree (id_terapeuta);


--
-- Name: idx_reservas_tratamiento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reservas_tratamiento ON public.reservas USING btree (id_tratamiento);


--
-- Name: idx_resultados_nivel_nivel; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resultados_nivel_nivel ON public.resultados_nivel USING btree (id_nivel);


--
-- Name: idx_resultados_nivel_paciente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resultados_nivel_paciente ON public.resultados_nivel USING btree (id_paciente);


--
-- Name: idx_sesiones_auth_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sesiones_auth_usuario ON public.sesiones_autenticacion USING btree (id_usuario);


--
-- Name: idx_sesiones_reserva; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sesiones_reserva ON public.sesiones USING btree (id_reserva);


--
-- Name: idx_tratamientos_expediente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tratamientos_expediente ON public.tratamientos USING btree (id_expediente);


--
-- Name: idx_tratamientos_terapeuta; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tratamientos_terapeuta ON public.tratamientos USING btree (id_terapeuta);


--
-- Name: idx_usuario_roles_asignado_por; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuario_roles_asignado_por ON public.usuario_roles USING btree (asignado_por);


--
-- Name: idx_usuario_roles_rol; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuario_roles_rol ON public.usuario_roles USING btree (id_rol);


--
-- Name: idx_usuario_roles_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuario_roles_usuario ON public.usuario_roles USING btree (id_usuario);


--
-- Name: actividades fk_actividades_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actividades
    ADD CONSTRAINT fk_actividades_paciente FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: administradores fk_administradores_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT fk_administradores_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: auditoria_cambios fk_auditoria_usuario_actor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria_cambios
    ADD CONSTRAINT fk_auditoria_usuario_actor FOREIGN KEY (id_usuario_actor) REFERENCES public.usuarios(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: conversaciones fk_conversaciones_terapeuta; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversaciones
    ADD CONSTRAINT fk_conversaciones_terapeuta FOREIGN KEY (id_terapeuta) REFERENCES public.terapeutas(id_terapeuta) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: conversaciones fk_conversaciones_tutor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversaciones
    ADD CONSTRAINT fk_conversaciones_tutor FOREIGN KEY (id_tutor) REFERENCES public.tutores(id_tutor) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: evaluaciones_ia fk_evaluaciones_ia_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones_ia
    ADD CONSTRAINT fk_evaluaciones_ia_paciente FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: evaluaciones_ia fk_evaluaciones_ia_reporte; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones_ia
    ADD CONSTRAINT fk_evaluaciones_ia_reporte FOREIGN KEY (id_reporte_sesion) REFERENCES public.reportes_sesion(id_reporte_sesion) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: evaluaciones_ia fk_evaluaciones_ia_resultado; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluaciones_ia
    ADD CONSTRAINT fk_evaluaciones_ia_resultado FOREIGN KEY (id_resultado_nivel) REFERENCES public.resultados_nivel(id_resultado_nivel) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: expedientes fk_expedientes_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expedientes
    ADD CONSTRAINT fk_expedientes_paciente FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: mensaje_adjuntos fk_mensaje_adjuntos_mensaje; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensaje_adjuntos
    ADD CONSTRAINT fk_mensaje_adjuntos_mensaje FOREIGN KEY (id_mensaje) REFERENCES public.mensajes(id_mensaje) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: mensajes fk_mensajes_conversacion; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT fk_mensajes_conversacion FOREIGN KEY (id_conversacion) REFERENCES public.conversaciones(id_conversacion) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: mensajes fk_mensajes_usuario_emisor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT fk_mensajes_usuario_emisor FOREIGN KEY (id_usuario_emisor) REFERENCES public.usuarios(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: mundos fk_mundos_actividad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mundos
    ADD CONSTRAINT fk_mundos_actividad FOREIGN KEY (id_actividad) REFERENCES public.actividades(id_actividad) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: niveles fk_niveles_mundo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.niveles
    ADD CONSTRAINT fk_niveles_mundo FOREIGN KEY (id_mundo) REFERENCES public.mundos(id_mundo) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: objetivos fk_objetivos_actividad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objetivos
    ADD CONSTRAINT fk_objetivos_actividad FOREIGN KEY (id_actividad) REFERENCES public.actividades(id_actividad) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: pacientes fk_pacientes_tutor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT fk_pacientes_tutor FOREIGN KEY (id_tutor) REFERENCES public.tutores(id_tutor) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: perfil_logros fk_perfil_logros_logro; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfil_logros
    ADD CONSTRAINT fk_perfil_logros_logro FOREIGN KEY (id_logro) REFERENCES public.logros(id_logro) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: perfil_logros fk_perfil_logros_perfil; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfil_logros
    ADD CONSTRAINT fk_perfil_logros_perfil FOREIGN KEY (id_perfil) REFERENCES public.perfiles(id_perfil) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: perfiles fk_perfiles_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfiles
    ADD CONSTRAINT fk_perfiles_paciente FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: reportes_sesion fk_reportes_sesion_sesion; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reportes_sesion
    ADD CONSTRAINT fk_reportes_sesion_sesion FOREIGN KEY (id_sesion) REFERENCES public.sesiones(id_sesion) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: reservas fk_reservas_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT fk_reservas_paciente FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: reservas fk_reservas_terapeuta; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT fk_reservas_terapeuta FOREIGN KEY (id_terapeuta) REFERENCES public.terapeutas(id_terapeuta) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: reservas fk_reservas_tratamiento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT fk_reservas_tratamiento FOREIGN KEY (id_tratamiento) REFERENCES public.tratamientos(id_tratamiento) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: resultados_nivel fk_resultados_nivel_nivel; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resultados_nivel
    ADD CONSTRAINT fk_resultados_nivel_nivel FOREIGN KEY (id_nivel) REFERENCES public.niveles(id_nivel) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: resultados_nivel fk_resultados_nivel_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resultados_nivel
    ADD CONSTRAINT fk_resultados_nivel_paciente FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: sesiones_autenticacion fk_sesiones_auth_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesiones_autenticacion
    ADD CONSTRAINT fk_sesiones_auth_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: sesiones fk_sesiones_reserva; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesiones
    ADD CONSTRAINT fk_sesiones_reserva FOREIGN KEY (id_reserva) REFERENCES public.reservas(id_reserva) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: terapeutas fk_terapeutas_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terapeutas
    ADD CONSTRAINT fk_terapeutas_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: tratamientos fk_tratamientos_expediente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tratamientos
    ADD CONSTRAINT fk_tratamientos_expediente FOREIGN KEY (id_expediente) REFERENCES public.expedientes(id_expediente) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: tratamientos fk_tratamientos_terapeuta; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tratamientos
    ADD CONSTRAINT fk_tratamientos_terapeuta FOREIGN KEY (id_terapeuta) REFERENCES public.terapeutas(id_terapeuta) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: tutores fk_tutores_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutores
    ADD CONSTRAINT fk_tutores_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: usuario_roles fk_usuario_roles_administrador; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fk_usuario_roles_administrador FOREIGN KEY (asignado_por) REFERENCES public.administradores(id_administrador) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: usuario_roles fk_usuario_roles_rol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fk_usuario_roles_rol FOREIGN KEY (id_rol) REFERENCES public.roles(id_rol) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: usuario_roles fk_usuario_roles_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fk_usuario_roles_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: actividades; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.actividades ENABLE ROW LEVEL SECURITY;

--
-- Name: administradores; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.administradores ENABLE ROW LEVEL SECURITY;

--
-- Name: auditoria_cambios; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.auditoria_cambios ENABLE ROW LEVEL SECURITY;

--
-- Name: conversaciones; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.conversaciones ENABLE ROW LEVEL SECURITY;

--
-- Name: evaluaciones_ia; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.evaluaciones_ia ENABLE ROW LEVEL SECURITY;

--
-- Name: expedientes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.expedientes ENABLE ROW LEVEL SECURITY;

--
-- Name: logros; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.logros ENABLE ROW LEVEL SECURITY;

--
-- Name: mensaje_adjuntos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.mensaje_adjuntos ENABLE ROW LEVEL SECURITY;

--
-- Name: mensajes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.mensajes ENABLE ROW LEVEL SECURITY;

--
-- Name: mundos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.mundos ENABLE ROW LEVEL SECURITY;

--
-- Name: niveles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.niveles ENABLE ROW LEVEL SECURITY;

--
-- Name: objetivos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.objetivos ENABLE ROW LEVEL SECURITY;

--
-- Name: pacientes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pacientes ENABLE ROW LEVEL SECURITY;

--
-- Name: perfil_logros; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.perfil_logros ENABLE ROW LEVEL SECURITY;

--
-- Name: perfiles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;

--
-- Name: reportes_sesion; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.reportes_sesion ENABLE ROW LEVEL SECURITY;

--
-- Name: reservas; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.reservas ENABLE ROW LEVEL SECURITY;

--
-- Name: resultados_nivel; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.resultados_nivel ENABLE ROW LEVEL SECURITY;

--
-- Name: roles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;

--
-- Name: sesiones; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.sesiones ENABLE ROW LEVEL SECURITY;

--
-- Name: sesiones_autenticacion; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.sesiones_autenticacion ENABLE ROW LEVEL SECURITY;

--
-- Name: terapeutas; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.terapeutas ENABLE ROW LEVEL SECURITY;

--
-- Name: tratamientos; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.tratamientos ENABLE ROW LEVEL SECURITY;

--
-- Name: tutores; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.tutores ENABLE ROW LEVEL SECURITY;

--
-- Name: usuario_roles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.usuario_roles ENABLE ROW LEVEL SECURITY;

--
-- Name: usuarios; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict uBlyrrHtgPRbnbG57vkKboiyL4hK1mNGXy8TKeHxtbN7UyBc870PtrfKX2RlGxb

