-- Ensayar/adoptar explícitamente después de 002; nunca ejecutado al iniciar la API.
BEGIN;
SET LOCAL lock_timeout = '5s';
ALTER TABLE public.reservas ALTER COLUMN id_tratamiento DROP NOT NULL;
ALTER TABLE public.reservas ADD COLUMN tipo_cita varchar(20) NOT NULL DEFAULT 'TERAPIA';
ALTER TABLE public.reservas ADD CONSTRAINT reservas_tipo_plan_ck CHECK (
  (tipo_cita = 'INTRODUCTORIA' AND id_tratamiento IS NULL) OR
  (tipo_cita = 'TERAPIA' AND id_tratamiento IS NOT NULL));
CREATE UNIQUE INDEX reservas_intro_pendiente_uq ON public.reservas(id_paciente)
  WHERE tipo_cita = 'INTRODUCTORIA' AND estado_reserva IN ('PENDIENTE', 'CONFIRMADA');
CREATE TABLE public.turnos_semanales (
  id_turno integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_terapeuta integer NOT NULL REFERENCES public.terapeutas(id_terapeuta) ON DELETE CASCADE,
  dia integer NOT NULL CHECK (dia BETWEEN 0 AND 5),
  hora integer NOT NULL CHECK (hora BETWEEN 8 AND 17),
  UNIQUE (id_terapeuta, dia, hora));
CREATE TABLE public.bloqueos_agenda (
  id_bloqueo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_terapeuta integer NOT NULL REFERENCES public.terapeutas(id_terapeuta) ON DELETE CASCADE,
  inicio timestamptz NOT NULL, fin timestamptz NOT NULL,
  CHECK (fin > inicio));
CREATE INDEX bloqueos_terapeuta_inicio_idx ON public.bloqueos_agenda(id_terapeuta, inicio);
ALTER TABLE public.turnos_semanales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bloqueos_agenda ENABLE ROW LEVEL SECURITY;
-- RLS/grants del rol runtime se revisan por entorno; sin acceso PUBLIC.
-- Reversión: requiere resolver introducciones sin plan antes de restaurar NOT NULL.
-- No borrar historial ni fabricar tratamientos para revertir.
COMMIT;
