-- Aplicación explícita tras004 por propietario; nunca al iniciar API ni en BD compartida sin aprobación.
BEGIN;
SET LOCAL lock_timeout = '5s';
CREATE TABLE public.preferencias_notificacion (
  id_usuario integer PRIMARY KEY REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
  nueva_cita boolean NOT NULL DEFAULT true,
  cancelacion boolean NOT NULL DEFAULT true,
  reprogramacion boolean NOT NULL DEFAULT true,
  recordatorio boolean NOT NULL DEFAULT true,
  mensajes boolean NOT NULL DEFAULT true
);
CREATE TABLE public.notificaciones (
  id_notificacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
  tipo varchar(30) NOT NULL CHECK (tipo IN ('NUEVA_CITA','CANCELACION','REPROGRAMACION','RECORDATORIO','MENSAJE')),
  titulo varchar(120) NOT NULL,
  texto text NOT NULL,
  id_reserva integer REFERENCES public.reservas(id_reserva) ON DELETE CASCADE,
  id_conversacion integer REFERENCES public.conversaciones(id_conversacion) ON DELETE CASCADE,
  clave_evento varchar(160) NOT NULL,
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  leida_en timestamptz,
  CONSTRAINT uq_notificacion_evento UNIQUE (id_usuario, clave_evento),
  CONSTRAINT ck_notificacion_recurso CHECK (
    (tipo = 'MENSAJE' AND id_conversacion IS NOT NULL AND id_reserva IS NULL) OR
    (tipo <> 'MENSAJE' AND id_reserva IS NOT NULL AND id_conversacion IS NULL))
);
CREATE INDEX notificaciones_usuario_fecha_idx ON public.notificaciones(id_usuario, fecha_creacion DESC, id_notificacion DESC);
CREATE INDEX notificaciones_sin_leer_idx ON public.notificaciones(id_usuario) WHERE leida_en IS NULL;
CREATE INDEX notificaciones_reserva_idx ON public.notificaciones(id_reserva) WHERE id_reserva IS NOT NULL;
CREATE INDEX notificaciones_conversacion_idx ON public.notificaciones(id_conversacion) WHERE id_conversacion IS NOT NULL;
CREATE INDEX reservas_recordatorio_idx ON public.reservas(fecha_hora_inicio) WHERE estado_reserva = 'CONFIRMADA';
ALTER TABLE public.notificaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preferencias_notificacion ENABLE ROW LEVEL SECURITY;
-- Auth propia: autorización por destinatario en FastAPI. Revisar GRANT/RLS runtime por entorno.
-- No grants a PUBLIC/anon/authenticated ni políticas Supabase Auth.
COMMIT;
-- Reversión conservadora: desactivar worker y volver a código previo; conservar avisos/preferencias.
