import type { View } from "@/types/navigation";
export const titles: Partial<Record<View, string>> = {
    padre: "Inicio",
    "padre/agenda": "Agenda",
    "padre/psicologos": "Terapeutas",
    "padre/compras": "Compras",
    "padre/recompensas": "Mundo ASHA",
    "padre/mensajes": "Mensajes",
    "padre/hijos": "Mis Hijos",
    "padre/progreso": "Progreso",
    "padre/reportes": "Reportes",
    "padre/config": "Configuración",
    "padre/camino": "Mi Camino ASHA",
    "padre/ayuda": "Centro de ayuda",
    "padre/recorrido": "Mi Camino ASHA",
    "padre/consentimiento": "Consentimiento",
    "padre/seguimiento": "Seguimiento",
    "padre/evaluacion": "Evaluación Inicial",
    "padre/incidencias": "Incidencias",
    "terapeuta/incidencias": "Incidencias",
    terapeuta: "Inicio",
    "terapeuta/agenda": "Agenda",
    "terapeuta/pacientes": "Pacientes",
    "terapeuta/mensajes": "Mensajes",
    "terapeuta/reportes": "Reportes",
    "terapeuta/analiticas": "Analíticas",
    "terapeuta/ingresos": "Pagos",
    "terapeuta/valoraciones": "Valoraciones",
    "terapeuta/config": "Configuración",
    "terapeuta/datos-actividad": "Datos de actividad",
    admin: "Dashboard",
    "admin/dashboard": "Dashboard",
    "admin/cuentas": "Gestión de Cuentas",
    "admin/terapeutas": "Terapeutas",
    "admin/operacion": "Operación",
    "admin/pagos": "Pagos",
    "admin/contenido": "Contenido",
    "admin/ml": "Machine Learning",
    "admin/auditoria": "Auditoría y seguridad",
    "admin/config": "Configuración",
    "mundo-asha": "Mundo ASHA",
    "mundo-asha/cuentos": "Cuentos",
    "mundo-asha/canciones": "Canciones",
    "mundo-asha/trabalenguas": "Trabalenguas",
    "mundo-asha/adivinanzas": "Adivinanzas",
    "mundo-asha/juegos": "Laboratorio",
    "mundo-asha/isla": "Isla Creativa",
    "mundo-asha/laberinto": "Laberinto de Trabalenguas",
    "mundo-asha/academia": "Academia",
    "mundo-asha/retos": "Retos",
    "mundo-asha/insignias": "Insignias",
    "mundo-asha/perfil": "Mi Perfil",
    session: "ASHA Session",
    "session/prep": "Preparación",
    "session/waiting": "Sala de espera",
    "session/active": "En sesión",
    "session/end": "Sesión finalizada",
    "session/summary": "Resumen",
    "session/rating": "Calificar",
    "session/rewards": "Recompensas",
    pay: "Pagos",
    "pay/history": "Historial de Pagos",
    "pay/wallet": "Pagos",
  };
