-- ============================================================
-- ASHAKids - Esquema base para Supabase / PostgreSQL
-- Basado en el diagrama ER final de ASHAKids
-- ============================================================

CREATE TABLE public.usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(60) NOT NULL,
    apellidos VARCHAR(80) NOT NULL,
    codigo_usuario VARCHAR(6) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(12) NOT NULL UNIQUE,
    descripcion VARCHAR(150),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.administradores (
    id_administrador INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL UNIQUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_administradores_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.tutores (
    id_tutor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL UNIQUE,
    parentesco VARCHAR(30),
    telefono VARCHAR(12),
    direccion VARCHAR(200),
    CONSTRAINT fk_tutores_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.terapeutas (
    id_terapeuta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL UNIQUE,
    especialidad VARCHAR(100),
    anios_experiencia INTEGER,
    idiomas VARCHAR(50),
    descripcion_profesional TEXT,
    CONSTRAINT fk_terapeutas_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_terapeutas_experiencia
        CHECK (anios_experiencia IS NULL OR anios_experiencia >= 0)
);

CREATE TABLE public.usuario_roles (
    id_usuario_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_rol INTEGER NOT NULL,
    asignado_por INTEGER,
    fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_usuario_roles_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_usuario_roles_rol
        FOREIGN KEY (id_rol) REFERENCES public.roles(id_rol)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_usuario_roles_administrador
        FOREIGN KEY (asignado_por) REFERENCES public.administradores(id_administrador)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT uq_usuario_rol UNIQUE (id_usuario, id_rol)
);

CREATE TABLE public.sesiones_autenticacion (
    id_sesion_auth INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    ultima_actividad TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    mfa_verificado BOOLEAN NOT NULL DEFAULT FALSE,
    revocado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_cierre TIMESTAMPTZ,
    CONSTRAINT fk_sesiones_auth_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.pacientes (
    id_paciente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tutor INTEGER NOT NULL,
    nombres_paciente VARCHAR(60) NOT NULL,
    apellidos_paciente VARCHAR(80) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    sexo VARCHAR(10) NOT NULL,
    avatar_nombre VARCHAR(20) NOT NULL DEFAULT 'zorro',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_pacientes_tutor
        FOREIGN KEY (id_tutor) REFERENCES public.tutores(id_tutor)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE public.expedientes (
    id_expediente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL UNIQUE,
    historial_clinico TEXT,
    diagnostico_inicial TEXT,
    fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_expedientes_paciente
        FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.tratamientos (
    id_tratamiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_expediente INTEGER NOT NULL,
    id_terapeuta INTEGER NOT NULL,
    nombre_tratamiento VARCHAR(100) NOT NULL,
    descripcion TEXT,
    sesiones_recomendadas INTEGER,
    estado_tratamiento VARCHAR(20) NOT NULL,
    fecha_inicio DATE,
    fecha_fin DATE,
    observaciones_cierre TEXT,
    CONSTRAINT fk_tratamientos_expediente
        FOREIGN KEY (id_expediente) REFERENCES public.expedientes(id_expediente)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_tratamientos_terapeuta
        FOREIGN KEY (id_terapeuta) REFERENCES public.terapeutas(id_terapeuta)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_tratamientos_sesiones
        CHECK (sesiones_recomendadas IS NULL OR sesiones_recomendadas >= 0)
);

CREATE TABLE public.reservas (
    id_reserva INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL,
    id_terapeuta INTEGER NOT NULL,
    id_tratamiento INTEGER NOT NULL,
    fecha_hora_inicio TIMESTAMPTZ NOT NULL,
    fecha_hora_fin TIMESTAMPTZ NOT NULL,
    modalidad VARCHAR(10) NOT NULL,
    localizacion VARCHAR(255),
    zoom_meeting_id VARCHAR(8),
    zoom_join_url VARCHAR(255),
    estado_reserva VARCHAR(20) NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_reservas_paciente
        FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_reservas_terapeuta
        FOREIGN KEY (id_terapeuta) REFERENCES public.terapeutas(id_terapeuta)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_reservas_tratamiento
        FOREIGN KEY (id_tratamiento) REFERENCES public.tratamientos(id_tratamiento)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_reservas_fechas
        CHECK (fecha_hora_fin > fecha_hora_inicio)
);

CREATE TABLE public.sesiones (
    id_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva INTEGER NOT NULL UNIQUE,
    fecha_hora_inicio_real TIMESTAMPTZ,
    fecha_hora_fin_real TIMESTAMPTZ,
    asistencia VARCHAR(20),
    estado_sesion VARCHAR(20) NOT NULL,
    CONSTRAINT fk_sesiones_reserva
        FOREIGN KEY (id_reserva) REFERENCES public.reservas(id_reserva)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_sesiones_fechas
        CHECK (
            fecha_hora_fin_real IS NULL
            OR fecha_hora_inicio_real IS NULL
            OR fecha_hora_fin_real > fecha_hora_inicio_real
        )
);

CREATE TABLE public.reportes_sesion (
    id_reporte_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion INTEGER NOT NULL UNIQUE,
    observaciones_iniciales TEXT,
    objetivos_trabajados TEXT,
    nivel_ayuda TEXT,
    proximos_pasos TEXT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_reportes_sesion_sesion
        FOREIGN KEY (id_sesion) REFERENCES public.sesiones(id_sesion)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.actividades (
    id_actividad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL,
    nombre_actividad VARCHAR(100) NOT NULL,
    descripcion TEXT,
    fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado_actividad VARCHAR(20) NOT NULL,
    CONSTRAINT fk_actividades_paciente
        FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.objetivos (
    id_objetivo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_actividad INTEGER NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    descripcion TEXT,
    resultados_objetivo JSONB,
    CONSTRAINT fk_objetivos_actividad
        FOREIGN KEY (id_actividad) REFERENCES public.actividades(id_actividad)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.mundos (
    id_mundo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_actividad INTEGER NOT NULL,
    nombre_mundo VARCHAR(50) NOT NULL,
    descripcion TEXT,
    objetivo TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_mundos_actividad
        FOREIGN KEY (id_actividad) REFERENCES public.actividades(id_actividad)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.niveles (
    id_nivel INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mundo INTEGER NOT NULL,
    nombre_nivel VARCHAR(100) NOT NULL,
    orden INTEGER NOT NULL,
    objetivo TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_niveles_mundo
        FOREIGN KEY (id_mundo) REFERENCES public.mundos(id_mundo)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_niveles_orden CHECK (orden > 0)
);

CREATE TABLE public.resultados_nivel (
    id_resultado_nivel INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL,
    id_nivel INTEGER NOT NULL,
    numero_intento INTEGER NOT NULL,
    puntaje INTEGER,
    estrellas_obtenidas INTEGER,
    detalle_resultados JSONB,
    fecha_realizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_resultados_nivel_paciente
        FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_resultados_nivel_nivel
        FOREIGN KEY (id_nivel) REFERENCES public.niveles(id_nivel)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_resultados_numero_intento CHECK (numero_intento > 0),
    CONSTRAINT chk_resultados_puntaje
        CHECK (puntaje IS NULL OR puntaje >= 0),
    CONSTRAINT chk_resultados_estrellas
        CHECK (estrellas_obtenidas IS NULL OR estrellas_obtenidas >= 0)
);

CREATE TABLE public.evaluaciones_ia (
    id_evaluacion_ia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL,
    id_reporte_sesion INTEGER NOT NULL,
    id_resultado_nivel INTEGER,
    resultado_json_ia JSONB,
    recomendaciones TEXT,
    estado_revision VARCHAR(20) NOT NULL,
    fecha_evaluacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_evaluaciones_ia_paciente
        FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_evaluaciones_ia_reporte
        FOREIGN KEY (id_reporte_sesion) REFERENCES public.reportes_sesion(id_reporte_sesion)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_evaluaciones_ia_resultado
        FOREIGN KEY (id_resultado_nivel) REFERENCES public.resultados_nivel(id_resultado_nivel)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE public.conversaciones (
    id_conversacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tutor INTEGER NOT NULL,
    id_terapeuta INTEGER,
    estado VARCHAR(20) NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ultima_actividad TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_archivado TIMESTAMPTZ,
    CONSTRAINT fk_conversaciones_tutor
        FOREIGN KEY (id_tutor) REFERENCES public.tutores(id_tutor)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_conversaciones_terapeuta
        FOREIGN KEY (id_terapeuta) REFERENCES public.terapeutas(id_terapeuta)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE public.mensajes (
    id_mensaje INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_conversacion INTEGER NOT NULL,
    id_usuario_emisor INTEGER,
    texto_mensaje TEXT,
    fecha_envio TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    leido BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_mensajes_conversacion
        FOREIGN KEY (id_conversacion) REFERENCES public.conversaciones(id_conversacion)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_mensajes_usuario_emisor
        FOREIGN KEY (id_usuario_emisor) REFERENCES public.usuarios(id_usuario)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE public.mensaje_adjuntos (
    id_adjunto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mensaje INTEGER NOT NULL,
    url_archivo VARCHAR(255) NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    tamano_bytes BIGINT NOT NULL,
    duracion_segundos INTEGER,
    CONSTRAINT fk_mensaje_adjuntos_mensaje
        FOREIGN KEY (id_mensaje) REFERENCES public.mensajes(id_mensaje)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_mensaje_adjuntos_tamano CHECK (tamano_bytes >= 0),
    CONSTRAINT chk_mensaje_adjuntos_duracion
        CHECK (duracion_segundos IS NULL OR duracion_segundos >= 0)
);

CREATE TABLE public.auditoria_cambios (
    id_auditoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario_actor INTEGER,
    nombre_tabla VARCHAR(50) NOT NULL,
    nombre_entidad VARCHAR(50) NOT NULL,
    accion VARCHAR(12) NOT NULL,
    datos_anteriores JSONB,
    datos_nuevos JSONB,
    fecha_evento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_auditoria_usuario_actor
        FOREIGN KEY (id_usuario_actor) REFERENCES public.usuarios(id_usuario)
        ON UPDATE CASCADE ON DELETE SET NULL
);


-- ============================================================
-- ÍNDICES
-- ============================================================

CREATE INDEX idx_usuario_roles_usuario
    ON public.usuario_roles(id_usuario);

CREATE INDEX idx_usuario_roles_rol
    ON public.usuario_roles(id_rol);

CREATE INDEX idx_usuario_roles_asignado_por
    ON public.usuario_roles(asignado_por);

CREATE INDEX idx_sesiones_auth_usuario
    ON public.sesiones_autenticacion(id_usuario);

CREATE INDEX idx_pacientes_tutor
    ON public.pacientes(id_tutor);

CREATE INDEX idx_tratamientos_expediente
    ON public.tratamientos(id_expediente);

CREATE INDEX idx_tratamientos_terapeuta
    ON public.tratamientos(id_terapeuta);

CREATE INDEX idx_reservas_paciente
    ON public.reservas(id_paciente);

CREATE INDEX idx_reservas_terapeuta
    ON public.reservas(id_terapeuta);

CREATE INDEX idx_reservas_tratamiento
    ON public.reservas(id_tratamiento);

CREATE INDEX idx_reservas_fecha_inicio
    ON public.reservas(fecha_hora_inicio);

CREATE INDEX idx_sesiones_reserva
    ON public.sesiones(id_reserva);

CREATE INDEX idx_actividades_paciente
    ON public.actividades(id_paciente);

CREATE INDEX idx_objetivos_actividad
    ON public.objetivos(id_actividad);

CREATE INDEX idx_mundos_actividad
    ON public.mundos(id_actividad);

CREATE INDEX idx_niveles_mundo
    ON public.niveles(id_mundo);

CREATE INDEX idx_resultados_nivel_paciente
    ON public.resultados_nivel(id_paciente);

CREATE INDEX idx_resultados_nivel_nivel
    ON public.resultados_nivel(id_nivel);

CREATE INDEX idx_evaluaciones_ia_paciente
    ON public.evaluaciones_ia(id_paciente);

CREATE INDEX idx_evaluaciones_ia_reporte
    ON public.evaluaciones_ia(id_reporte_sesion);

CREATE INDEX idx_evaluaciones_ia_resultado
    ON public.evaluaciones_ia(id_resultado_nivel);

CREATE INDEX idx_conversaciones_tutor
    ON public.conversaciones(id_tutor);

CREATE INDEX idx_conversaciones_terapeuta
    ON public.conversaciones(id_terapeuta);

CREATE INDEX idx_mensajes_conversacion
    ON public.mensajes(id_conversacion);

CREATE INDEX idx_mensajes_emisor
    ON public.mensajes(id_usuario_emisor);

CREATE INDEX idx_mensaje_adjuntos_mensaje
    ON public.mensaje_adjuntos(id_mensaje);

CREATE INDEX idx_auditoria_usuario_actor
    ON public.auditoria_cambios(id_usuario_actor);

CREATE INDEX idx_auditoria_tabla_entidad
    ON public.auditoria_cambios(nombre_tabla, nombre_entidad);

CREATE INDEX idx_auditoria_fecha_evento
    ON public.auditoria_cambios(fecha_evento);


-- ============================================================
-- GAMIFICACIÓN Y PERFILES (Fase 3A)
-- ============================================================

CREATE TABLE public.perfiles (
    id_perfil INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL UNIQUE,
    progreso NUMERIC(5,2) NOT NULL DEFAULT 0.0,
    racha_dias INTEGER NOT NULL DEFAULT 0,
    objetivos_totales INTEGER NOT NULL DEFAULT 0,
    objetivos_completados INTEGER NOT NULL DEFAULT 0,
    actividades_desarrolladas_total INTEGER NOT NULL DEFAULT 0,
    sesiones_totales INTEGER NOT NULL DEFAULT 0,
    fecha_ultima_sesion TIMESTAMPTZ,
    experiencia INTEGER NOT NULL DEFAULT 0,
    nivel INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_perfiles_paciente
        FOREIGN KEY (id_paciente) REFERENCES public.pacientes(id_paciente)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.logros (
    id_logro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_logro VARCHAR(100) NOT NULL,
    experiencia_logro INTEGER NOT NULL DEFAULT 0,
    requisito_logro TEXT NOT NULL,
    icono_logro VARCHAR(255)
);

CREATE TABLE public.perfil_logros (
    id_perfil_logro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_perfil INTEGER NOT NULL,
    id_logro INTEGER NOT NULL,
    fecha_obtencion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_perfil_logros_perfil
        FOREIGN KEY (id_perfil) REFERENCES public.perfiles(id_perfil)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_perfil_logros_logro
        FOREIGN KEY (id_logro) REFERENCES public.logros(id_logro)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_perfil_logro UNIQUE (id_perfil, id_logro)
);

CREATE INDEX idx_perfiles_paciente ON public.perfiles(id_paciente);
CREATE INDEX idx_perfil_logros_perfil ON public.perfil_logros(id_perfil);
CREATE INDEX idx_perfil_logros_logro ON public.perfil_logros(id_logro);


-- ============================================================
-- DATOS INICIALES
-- ============================================================

INSERT INTO public.roles (nombre_rol, descripcion)
VALUES
    ('PADRE', 'Usuario con perfil de tutor o padre de familia'),
    ('TERAPEUTA', 'Profesional encargado de la terapia'),
    ('ADMIN', 'Administrador de la plataforma')
ON CONFLICT (nombre_rol) DO NOTHING;


-- ============================================================
-- FIN DEL ESQUEMA BASE ASHAKids
-- ============================================================
